#####
# Docker Compose for NextCloud stack
#
# Based on the nextcloud+PostGres example from github.com/docker/awesome-compose
#####

services:
  ###### NEXTCLOUD ######
  nc:
    image: nextcloud:apache
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: unless-stopped
    volumes:
      - nc_vol:/var/www/html
    networks:
      - cloud_redis
      - cloud_db

  ###### POSTGRES DB ######
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: unless-stopped
    networks:
      - cloud_db
    volumes:
      - db_vol:/var/lib/postgresql/data
    expose:
      - 5432

  ###### REDIS ######
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - cloud_redis
    expose:
      - 6379

  ##### Collabora Code Server #####
  office:
    image: collabora/code:latest
    container_name: ncoffice
    volumes:
      - coolwsd_vol:/etc/coolwsd
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      - username=admin # Different in production
      - password=admin # Different in production
      - aliasgroup1=https://cloud.zyming.me:443
      - aliasgroup2=https://office.zyming.me:443
      - dictionaries="en_GB en_US sv_SE zh_CN ja_JP"

volumes:
  db_vol:
  nc_vol:
  coolwsd_vol:

networks:
  cloud_redis:
  cloud_db:
